### ISSUE TITLE
How can data items be deleted?

### ISSUE THREAD

**Issue by nat32support** [melvincarvalho/userguide#2]
I'm testing with a solid.community profile and can see no way of deleting items I've dropped to the Public Folder. Please explain how this is done.

**Comment by pavittarx** [comment]
@nat32support 
1. Open your solid community profile,
2. Navigate to and open File/Folder you want to Delete
4. Now, move your cursor over the name of the file or Folder. You will see some icons showing up.
5.  Click on the 'Settings' icon 
![image](https://user-images.githubusercontent.com/29155477/46451992-fc8eea80-c7b6-11e8-941e-aaad3f1e5f95.png)


6. Now hover your mouse cursor to the left of the 'Refresh icon'. A red colored 'Remove' icon will become visible. 
![image](https://user-images.githubusercontent.com/29155477/46452008-16c8c880-c7b7-11e8-83f6-16c1ba4ab12f.png)


7. Click it & Confirm deletion.

**Comment by melvincarvalho** [comment]
Thanks, I didnt even know about that! :D

**Comment by melvincarvalho** [comment]
This is quite a good one to add to the guide ...

**Comment by pavittarx** [comment]
@melvincarvalho I guess so, I just stumbled upon it while experimenting through my pod,  and I saw this question. It didn't took much, infact the UI is kind of buggy, and do not behave well enough, 
An average user is certainly going to be running away. I believe it is experimental and they will fix it to something better. 

* The back navigation button is missing. 
* I have to edit the URL for navigating back to the main directory. 
* It is kind of hard to guess, what is what. The UI can be better from what it is now, it feels very hard to navigate in my own pod. even though it has nothing.
*  I don't know where to reach support to give in my suggestion, or contribute. (Suggest if you know one)

The best thing that can happen to me is, A new kind of error has just shown up in my pod, not allowing me to delete a random note I created. 

----

1. You should add how those icons appear.
2. What each icon is for. 
3. What kind of data can be created. 


It will be more useful, thanks.
